#!/usr/bin/env bash
#Create a page to use redirect permanent in nginx default file
sudo touch /usr/share/nginx/html/redirect_me
sudo sed -i '26 i \     rewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
