#!/usr/bin/env bash
#very bare version of init.d/command start. no check for multiple instances
if [ x"$1" = "xstart" ];
then
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ x"$1" = "xstop" ];
then
    kill "$(cat /var/run/my_process.pid)"
    rm -f /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [ x"$1" = "xrestart" ];
then
    kill "$(cat /var/run/my_process.pid)"
    rm -f /var/run/my_process.pid
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
echo "Usage: manage_my_process {start|stop|restart}"
fi
