#!/usr/bin/env bash
# This is a script that uses while and if/elif/else to display strings
i=1
while [ $i -le 10 ];
do
if [ $i -eq 4 ];
then
echo "bad luck"
elif [ $i -eq 8 ];
then
echo "good luck"
else
echo "Holberton School"
fi
let "++i"
done
